project:
  type: website
  output-dir: docs
  resources:
    - "img_cm/"
    - "articles"
website:
  title: "Empires and American Identity: A C Miller Presentation"
  navbar:
    left:
      - about.qmd
      - icon: github
        href: https://github.com/miller-c-r
format:
  html:
    theme: lux
    css: styles.css

editor: visual
